[package]
name = "trait_cast_rs"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc"]
downcast_unchecked = ["trait_cast_impl_rs/downcast_unchecked"]
alloc = []
min_specialization = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trait_cast_impl_rs = { path = "../trait_cast_impl_rs" }
