[package]
name = "trait_cast_rs"
version = "0.1.0"
edition = "2021"

[features]
default = []
downcast_unchecked = ["trait_cast_impl_rs/downcast_unchecked"]
alloc = ["downcast_unchecked"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trait_cast_impl_rs = { path = "../trait_cast_impl_rs" }
